# Generated by Django 2.1 on 2019-10-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actividades', models.CharField(max_length=45)),
                ('MantenimientoP', models.CharField(max_length=45)),
                ('MantenimientoC', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('FechaViso', models.DateField()),
            ],
        ),
    ]
